[录制设置]
language(zh_cn/en) = zh_cn
是否跳过代理检测(是/否) = 否
直播保存路径(不填则默认) = 
保存文件夹是否以作者区分 = 是
保存文件夹是否以时间区分 = 否
保存文件夹是否以标题区分 = 否
保存文件名是否包含标题 = 否
是否去除名称中的表情符号 = 是
视频保存格式ts|mkv|flv|mp4|mp3音频|m4a音频 = ts
原画|超清|高清|标清|流畅 = 流畅
是否使用代理ip(是/否) = 是
代理地址 = 
同一时间访问网络的线程数 = 3
循环时间(秒) = 300
排队读取网址时间(秒) = 0
是否显示循环秒数 = 否
是否显示直播源地址 = 否
分段录制是否开启 = 是
是否强制启用https录制 = 否
录制空间剩余阈值(gb) = 1.0
视频分段时间(秒) = 1800
录制完成后自动转为mp4格式 = 否
mp4格式重新编码为h264 = 否
追加格式后删除原文件 = 是
生成时间字幕文件 = 否
是否录制完成后执行自定义脚本 = 否
自定义脚本执行命令 = 
使用代理录制的平台(逗号分隔) = tiktok, sooplive, pandalive, winktv, flextv, popkontv, twitch, liveme, showroom, chzzk, shopee, shp, youtu
额外使用代理录制的平台(逗号分隔) = 

[推送配置]
# 可选微信|钉钉|tg|邮箱|bark|ntfy|pushplus 可填多个
直播状态推送渠道 =
钉钉推送接口链接 =
微信推送接口链接 =
bark推送接口链接 =
bark推送中断级别 = active
bark推送铃声 =
钉钉通知@对象(填手机号) =
钉钉通知@全体(是/否) = 否
tgapi令牌 =
tg聊天id(个人或者群组id) =
smtp邮件服务器 =
是否使用SMTP服务SSL加密(是/否) =
SMTP邮件服务器端口 =
邮箱登录账号 =
发件人密码(授权码) =
发件人邮箱 =
发件人显示昵称 =
收件人邮箱 =
ntfy推送地址 = https://ntfy.sh/xxxx
ntfy推送标签 = tada
ntfy推送邮箱 =
pushplus推送token =
自定义推送标题 =
自定义开播推送内容 =
自定义关播推送内容 =
只推送通知不录制(是/否) = 否
直播推送检测频率(秒) = 1800
开播推送开启(是/否) = 是
关播推送开启(是/否)= 否

[Cookie]
# 录制抖音必填
抖音cookie = enter_pc_once=1; UIFID_TEMP=48df845ec17e24d3e136cf9cb5f33ae5ff0d6a60613b8e70d731bae9b37d4b93948da90e2f1ebd3fcc50080e4bfe5eb4280880db444bcefd805d2696b90bdad9cf6ee90b49bec6841699e40d35122c0c; hevc_supported=true; bd_ticket_guard_client_web_domain=2; passport_csrf_token=3020e99701eeabec482720ba4832ae97; passport_csrf_token_default=3020e99701eeabec482720ba4832ae97; passport_mfa_token=CjfR5M8S%2FoOnpZ3sOLfxnDMGRY4h1QdekjdVSNXmrEJCxfYUlzxSxRb2kVb4clE77yNyxte4jJQ3GkoKPAAAAAAAAAAAAABQI00iDmuGjIK%2FRwjJPBwyMaYSPu%2BLm4%2BFOIlZ6zoXbWXaO84YxVwVqgUCPC5yplr7FBDokYsOGPax0WwgAiIBA60J2Z8%3D; d_ticket=a319d442240458251934771ede009bd769399; passport_assist_user=CkFNpRe0nb5CjiqAbKmWMmBWPDCYR8CStt-MBdgcDieSqGa-sUUJts2Y2VomZI41Im3ygd-zn55qCT0NE5g_q9WIuxpKCjwAAAAAAAAAAAAAUCNAidrymqbJ6D1jy31sqbtJNq1pSNNNOWAPtfqoxlRMfIcjF860HcNiGxaY7n7yHwMQ4ZCLDhiJr9ZUIAEiAQMowek_; n_mh=mC1Pbj2OKPV24yOVcUkL5uVoFW6EAoaGyr_7euK36Bo; passport_auth_status=8774a3bb3619ff4eb4a5c8df2c255901%2C; passport_auth_status_ss=8774a3bb3619ff4eb4a5c8df2c255901%2C; sid_guard=c5024a3836a9766068afcc06c0504c94%7C1772562073%7C5184000%7CSat%2C+02-May-2026+18%3A21%3A13+GMT; uid_tt=a450e266fcd9797105ef5757ed049d08; uid_tt_ss=a450e266fcd9797105ef5757ed049d08; sid_tt=c5024a3836a9766068afcc06c0504c94; sessionid=c5024a3836a9766068afcc06c0504c94; sessionid_ss=c5024a3836a9766068afcc06c0504c94; session_tlb_tag=sttt%7C5%7CxQJKODapdmBor8wGwFBMlP________-j2iIarBLPMyWGJc_5yTwIG7ukg5Of3WhblH-sWec6i7U%3D; is_staff_user=false; sid_ucp_v1=1.0.0-KGQ0OWU5MGE0NmZkOWEwZTJjNDEzZTE5MjFhYzhjOGNmZDViYzk0M2MKIQjL7LCQ3vWwBBCZzZzNBhjvMSAMMNLD-OYFOAJA8QdIBBoCaGwiIGM1MDI0YTM4MzZhOTc2NjA2OGFmY2MwNmMwNTA0Yzk0; ssid_ucp_v1=1.0.0-KGQ0OWU5MGE0NmZkOWEwZTJjNDEzZTE5MjFhYzhjOGNmZDViYzk0M2MKIQjL7LCQ3vWwBBCZzZzNBhjvMSAMMNLD-OYFOAJA8QdIBBoCaGwiIGM1MDI0YTM4MzZhOTc2NjA2OGFmY2MwNmMwNTA0Yzk0; _bd_ticket_crypt_cookie=3e9f8240ef45968aec532408cdeb7fd0; __security_server_data_status=1; login_time=1772562075009; UIFID=48df845ec17e24d3e136cf9cb5f33ae5ff0d6a60613b8e70d731bae9b37d4b93948da90e2f1ebd3fcc50080e4bfe5eb4c758adae7af25cc599ce7be7ed3885f67969da555b634ab8a3dd3ee3c6c5d5a2c0d94cce9b484df315bdea3f035690984429e5813574c533d2c66bda4f0ab211c8abd62c810957cb5558f1867872ad5549795dc23096013e905b3cfa09d4d4ad8655a373621069d552b260c3d8e551a1; is_dash_user=1; my_rd=2; SEARCH_RESULT_LIST_TYPE=%22single%22; publish_badge_show_info=%220%2C0%2C0%2C1773480653396%22; download_guide=%220%2F%2F1%22; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Afalse%2C%22volume%22%3A0.8%7D; strategyABtestKey=%221773480813.209%22; ttwid=1%7CIks4gFFgGW-UBIsDQ6phP5-Bj3NltuR4UDto8wuU610%7C1773480809%7C8d86cb23c9c621965b73d402750cb628c105f74f6ef5201b3dedc02de8b9942d; FOLLOW_NUMBER_YELLOW_POINT_INFO=%22MS4wLjABAAAAKHqQGL9CqGAj7V1cw5EKUI9pqvpNOSQF1plX7Wnpa1aqhQ8pqvPAWfrzRpfZOQ9I%2F1773504000000%2F0%2F0%2F0%22; vdg_s=1; __security_mc_1_s_sdk_crypt_sdk=80f65167-4cfa-b86d; __security_mc_1_s_sdk_cert_key=49b6dd73-4a29-842f; __security_mc_1_s_sdk_sign_data_key_web_protect=cce6c272-45d7-aa2f; playRecommendGuideTagCount=6; totalRecommendGuideTagCount=6; FOLLOW_LIVE_POINT_INFO=%22MS4wLjABAAAAKHqQGL9CqGAj7V1cw5EKUI9pqvpNOSQF1plX7Wnpa1aqhQ8pqvPAWfrzRpfZOQ9I%2F1773504000000%2F0%2F1773485690615%2F0%22; IsDouyinActive=true; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A12%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A50%7D%22; SelfTabRedDotControl=%5B%7B%22id%22%3A%227207001807963293736%22%2C%22u%22%3A130%2C%22c%22%3A0%7D%2C%7B%22id%22%3A%227427696861776971814%22%2C%22u%22%3A26%2C%22c%22%3A0%7D%2C%7B%22id%22%3A%227471867636853606441%22%2C%22u%22%3A64%2C%22c%22%3A0%7D%2C%7B%22id%22%3A%227398975745248200755%22%2C%22u%22%3A245%2C%22c%22%3A0%7D%5D; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCRU5JelA5SW5pUllWUTBncWZZcU5PN2Npbnd3a3Y0SFhEeVY2VHlzdFo3OTN5SmhLMVE1dEU1ZDNvRkhLUzJWSys3VGEzYnQxdGx5MEVZQVNjc1dPSGM9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoyfQ%3D%3D; home_can_add_dy_2_desktop=%221%22; odin_tt=58164f392801a279b6d03976f5e9a416150785685338730060bfd006a9db7e73fb385e795b600249aaba4f346c7a5c37299d2193442bb42e46f8d0511449a2c6; sdk_source_info=7e276470716a68645a606960273f276364697660272927676c715a6d6069756077273f276364697660272927666d776a68605a607d71606b766c6a6b5a7666776c7571273f275e58272927666a6b766a69605a696c6061273f27636469766027292762696a6764695a7364776c6467696076273f275e582729277672715a646971273f2763646976602729277f6b5a666475273f2763646976602729276d6a6e5a6b6a716c273f2763646976602729276c6b6f5a7f6367273f27636469766027292771273f273132303d373134323036323234272927676c715a75776a716a666a69273f2763646976602778; bit_env=xmHe3fLGLobSjJREpvaBMfuihRHbzQHD_R0zEfDY5_ysPwGLCPiDqDVf38hIM1L4mElCLeP6c0FStMf351t2dvWTtlpeuVCxIBe_Fy_FEEChkmVKtUWg02d-JFqJQA2_ylMdgdcBDLiJ7iCy-fSfJLhH7lAjHG4buVa3ykt8laHp-_z0Ye4kxc0zSzZgQSEtkp6XNtK0CQdhJOsyt-jUEAbUJFHyZDc3-Te-wQOjH7YDdQUFODBPxSTMN1Ik8XZudC0x9Oa64hyRK0UfbdqVFvpeWLzqC7lWXsSw_mkNkwaEdB_Lzn5qD3T2DgojWb9inmays7FQyrR-46GaoEvIkNRG9ljVbxcVh30GexBn5gC25QW4wuD19RTtlQ_8AXX_cNs1HNPkp03ei8I1yxLHKSQDLk6tZ-7NVYuUZ7yIXysyLRWJJCvcXxnDQ7MLCQnTOenlmT63J-ZjpRCHEagGvhKhoM6kIDnuAKok69tQaxDH_udhJLze8hci9sVJ0NM0OpL4eO_vOhzbsdjtBdyPQYzg_jHeoy3RGcMJced0RCs%3D; gulu_source_res=eyJwX2luIjoiMTFjNzA1YmRiZTExNmNmYjhiODQyNDUwNTVmMmJiZTEzYjg1MGIyMmUwYzcyMzk0MGM5NzVkNzY0YWFlNDU0YyJ9; passport_auth_mix_state=ub5k61adxpjbh7l1dnqhtnfhl7r5djg9rl6lfs26v4j6tiz0; biz_trace_id=860af88d; bd_ticket_guard_client_data_v2=eyJyZWVfcHVibGljX2tleSI6IkJFTkl6UDlJbmlSWVZRMGdxZllxTk83Y2lud3drdjRIWER5VjZUeXN0Wjc5M3lKaEsxUTV0RTVkM29GSEtTMlZLKzdUYTNidDF0bHkwRVlBU2NzV09IYz0iLCJ0c19zaWduIjoidHMuMi5iZTBhMTNkZWNlMzQ5NGI0YTJlZDYwOWUxMjliMThmZDUwODRiZTc5ZGE3YWMwZGYzYzBlYTU0YTQxMTE1YTdiYzRmYmU4N2QyMzE5Y2YwNTMxODYyNGNlZGExNDkxMWNhNDA2ZGVkYmViZWRkYjJlMzBmY2U4ZDRmYTAyNTc1ZCIsInJlcV9jb250ZW50Ijoic2VjX3RzIiwicmVxX3NpZ24iOiJhNFk4M0hmcmNyWXA4MjVnVEVMRklUVUJTL012cVZuUnRFWnZ5RVBONk1jPSIsInNlY190cyI6IiNTbjlwVFMyZnllTmxQWHFMOUYzbzlOb0VjRERjd0EybjhhNDlvb1JqL3dMVERtNGxoRU92UUhwSDkvRlQifQ%3D%3D
快手cookie =
tiktok_cookie =
虎牙cookie =
斗鱼cookie =
yy_cookie =
b站cookie =
小红书cookie =
bigo_cookie =
blued_cookie =
sooplive_cookie =
netease_cookie =
千度热播_cookie =
pandatv_cookie =
猫耳fm_cookie =
winktv_cookie =
flextv_cookie =
look_cookie =
twitcasting_cookie =
baidu_cookie =
weibo_cookie =
kugou_cookie =
twitch_cookie =
liveme_cookie =
huajiao_cookie =
liuxing_cookie =
showroom_cookie =
acfun_cookie =
changliao_cookie =
yinbo_cookie =
yingke_cookie =
zhihu_cookie =
chzzk_cookie =
haixiu_cookie =
vvxqiu_cookie =
17live_cookie =
langlive_cookie =
pplive_cookie =
6room_cookie =
lehaitv_cookie =
huamao_cookie =
shopee_cookie =
youtube_cookie =
taobao_cookie =
jd_cookie =
faceit_cookie =
migu_cookie =
lianjie_cookie =
laixiu_cookie =
picarto_cookie =


[Authorization]
popkontv_token =

[账号密码]
sooplive账号 =
sooplive密码 =
flextv账号 =
flextv密码 =
popkontv账号 =
partner_code = P-00001
popkontv密码 =
twitcasting账号类型 = normal
twitcasting账号 =
twitcasting密码 =
